### ISSUE TITLE
Android - 程序报错

### ISSUE THREAD

**Issue by freebooterish** [tencentyun/TRTCFlutterScenesDemo#3]
【当前现象】：编译报错
【SDKAppID】：1400547280
【日志或者描述、截图】：
**TRTCChatSalonImpl.dart:**
The argument type 'int' can't be assigned to the parameter type 'String'.
The argument type 'String' can't be assigned to the parameter type 'int'.
**TRTCLiveRoomImpl.dart:**
The argument type 'int' can't be assigned to the parameter type 'String'.
The argument type 'String' can't be assigned to the parameter type 'int'.

**Comment by Tonigt** [comment]
自己改了就成了，这是很简单的类型错误，哈哈哈
