### ISSUE TITLE
Android x86模拟器闪退

### ISSUE THREAD

**Issue by gongxiaosan** [tencentyun/TRTCFlutterScenesDemo#6]
真机可以正常运行

E/AndroidRuntime: FATAL EXCEPTION: TRTCCloudApi
    Process: , PID: 14463
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.audio.impl.TXCAudioEngineJNI.nativeCacheClassForNative()

**Comment by c1avie** [comment]
安卓不支持模拟器运行哈，请使用真机
