### ISSUE TITLE
updateLocalView和updateRemoteView接口

### ISSUE THREAD

**Issue by lan2001** [tencentyun/TRTCFlutterScenesDemo#7]
(https://pub.flutter-io.cn/packages/tencent_trtc_cloud/changelog) 更新日志中

1.2.3  安卓端支持updateLocalView和updateRemoteView接口
今天使用1.3.0版本进行测试，发现安卓这边调用updateLocalView接口并没有起作用，ios这边倒是有。

接口里面也有下面说明，所以安卓端还是不支持吗?
  ```
/// 更新本地视频预览画面的窗口,仅仅ios有效
  ///
  /// 参数：
  ///
  /// viewId	承载视频画面的控件
  Future<void> updateLocalView(viewId) {
    return _channel.invokeMethod('updateLocalView', {
      "viewId": viewId,
    });
  }
```

**Comment by lan2001** [comment]
还有一个安卓端使用TRTCCloud().registerListener()问题

用户A监听不到用户B的TRTCCloudListener.onUserVideoAvailable开启摄像头事件。但能收到用户B的关闭摄像头事件，也能收到开启或者关闭麦克风的事件。

复现：用户A进入直播开启摄像头，用户B进入直播开启摄像头，等待15秒以上，用户B退出直播间，等待5秒，用户B再次进入直播间，此时用户B开启摄像头，但是用户A监听不到用户B开启摄像头事件。该现象必出现。

tencent_trtc_cloud 1.3.0 出现该问题，回退tencent_trtc_cloud 1.2.7 版本测试无此问题。

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)

```

**Comment by c1avie** [comment]
安卓这边有点特殊，updateView时需要把TRTCCloudVideoView的viewType指定为TRTCCloudDef.TRTC_VideoView_TextureView才有效

**Comment by xionghaoo** [comment]
@c1avie 现在1.3.0版本sdk可以切换Android端的大小画面了，但是切换以后本地视频画面会变形
changeVideoView() {
    if (_callingScenes == CallingScenes.AudioOneVOne ||
        _currentCallStatus == CallStatus.calling) return;
    isChangeBigSmallVideo = !isChangeBigSmallVideo;
    //为false的时候，在已接听状态的时候。小画面显示本地视频，大画面显示远端视频。
    if (isChangeBigSmallVideo) {
      _tRTCCallingService.updateLocalView(_bigVideoViewId);
      _tRTCCallingService.updateRemoteView(_remoteUserInfo!.userId,
          TRTCCloudDef.TRTC_VIDEO_STREAM_TYPE_BIG, _smallVideoViewId);
    } else {
      _tRTCCallingService.updateLocalView(_smallVideoViewId);
      _tRTCCallingService.updateRemoteView(_remoteUserInfo!.userId,
          TRTCCloudDef.TRTC_VIDEO_STREAM_TYPE_BIG, _bigVideoViewId);
    }
  }
