### ISSUE TITLE
Android端视频通话时，切换大小视频画面，本地视频画面变形

### ISSUE THREAD

**Issue by xionghaoo** [tencentyun/TRTCFlutterScenesDemo#8]
issue标题：

【Android】-【1.3.0】Android端视频通话时，切换大小视频画面变形

issue内容：

【当前现象】：Android端视频通话时，调用changeVideoView切换大小画面，本地视频画面会变形
【SDKAppID】：1400577044
【房间号】:
【useID】：
【问题时间段】：
【机型】：Nexus6P
【之前版本有无此问题】：
【是否必现】：必现 ，
【复现方法】：Demo的changeVideoView方法
【日志或者描述、截图】：如有请附上相关日志，方便我们定位，如有截图更好

-------------------------完整的示例如下：-------------------------

SDK版本：tencent_trtc_cloud: ^1.3.0

调用代码：
```dart
  changeVideoView() {
    if (_callingScenes == CallingScenes.AudioOneVOne ||
        _currentCallStatus == CallStatus.calling) return;

    isChangeBigSmallVideo = !isChangeBigSmallVideo;
    //为false的时候，在已接听状态的时候。小画面显示本地视频，大画面显示远端视频。
    if (isChangeBigSmallVideo) {
      _tRTCCallingService.updateLocalView(_bigVideoViewId);
      _tRTCCallingService.updateRemoteView(_remoteUserInfo!.userId,
          TRTCCloudDef.TRTC_VIDEO_STREAM_TYPE_BIG, _smallVideoViewId);
    } else {
      _tRTCCallingService.updateLocalView(_smallVideoViewId);
      _tRTCCallingService.updateRemoteView(_remoteUserInfo!.userId,
          TRTCCloudDef.TRTC_VIDEO_STREAM_TYPE_BIG, _bigVideoViewId);
    }
  }
```

![Screenshot_20211203-151147050](https://user-images.githubusercontent.com/15957437/144561793-2b1b1a75-01b5-4305-b770-b1228d581f50.jpg)

![Screenshot_20211203-151228591](https://user-images.githubusercontent.com/15957437/144561967-a0944b01-cf26-4555-bf62-976e44d8e1ec.jpg)

**Comment by c1avie** [comment]
view的大小是怎样设置的，Demo可以复现吗，我跑了下Demo，不会变形

**Comment by c1avie** [comment]
我这边先关闭了该issue，如果您这边还有问题，欢迎再次打开
